# Site settings
title: "Kristen & Ty"
description: |
    Ijamsville, Maryland

    November 02, 2019
owner: Tyler B
first_published: 2018
email: tybolt@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "tyandkristen.com" # the base hostname & protocol for your site

social:
  github: https://github.com/tbolt/wedding-site

# Build settings
markdown: kramdown
